language: java

jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "littlegrid"
    token:
      secure: "oxSGa22r98imGkMfS3XNhN51iunS/d9JsB19V7/gb2javpgu05hojH1EbWJARMrLrOmeEA3YL7xsmmKt/HvnOFFWfFGFV4hqVPcujZu95cufUrtgFP3xPUQfTxgCASsfNYG8AiZcgDoLXggM6crjMLIWYAc+meHmxteGNL9WGvq1Wx33Ib1miTru7TCJ7bG9uwjryVq6mAnJcNUbFM2VvU5X69VZuXUU8dmQqPFlQT/1gDKbA9nER7w4k2nvUyBeDTi/7/qh/WP1/vA68Vz0pLBsdPyVPVAGWbx2i2cIlZi3z65ul35GnVuwW1K+ntopbyeZGtj+GLx8UAVm5gu++MyGQvZSfAfL1yUnsMpX11HSA7awYzLj8EZY5zwBOgJo6tJ+RGB0bv2OLLDfK8JKd52pT0Xte5WoZCbY386G0keEhC+/bK2H03A6qz0h1WHvlc0pDVO2iB13k2L6pNQwzBV5ilY6Ce2lbaTbL+ReruiaSeNBEV8muAmIORT0UUz6gVqilc0Hm24j83LTOp43fi6eIXtPRevJnfv/EE3oNZUJP3yc9WcUNcQ2BLr0uREzjCTNUiROPtwWn5FBYVAdxiMspiZspPcgPfzO7mWQ3ruLa7By2OPOZDt9uFjecMLbI8+0N7go2xinVgOK5S/PSAlR/BpU769CjaDvpRk5fuQ="
 
script:
  - mvn clean verify sonar:sonar -Pcoverage
